---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=djangoblog.conf.j2 dest=/etc/init/djangoblog.conf

- name: Start gunicorn Upstart Job
  sudo: yes
  service: name=djangoblog state=restarted
