keypair: pk-aws
security_group: vpc-ssh-access
instance_type: t2.micro
ami: ami-29ebb519
vpc_subnet_id: subnet-29b9a46f
region: us-west-2
instance_tags: {"Name": "ansible-built"}
root_ebs_size: 8
zone: us-west-2c
instance_profile_name: mypoweruser
num_instances: 1
